model_list:
  - model_name: cs-ai-model
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY
      priority: 1
  - model_name: cs-ai-model
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
      priority: 2

router_settings:
  routing_strategy: simple-shuffle
  set_verbose: True
